server:
  port: 8084

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/userservicedb?createDatabaseIfNotExist=true
#    username: root
#    password: axyroxxx
    username: epiz_26804015
    password: RLHGYYW0YLiNA6L
    database: epiz_26804015_userservicedb
    host: sql110.epizy.com
#    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
